version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=toman_shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./backend/.env

  django_app:
    build:
      context: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./backend:/app/
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    restart: on-failure

  migrations:
    build:
      context: ./backend
    command: python manage.py migrate
    depends_on:
      - db
    restart: on-failure

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8080:80"
    depends_on:
      - django_app
volumes:
  static_volume:
  media_volume: